---
- hosts: all
  become: yes
  tasks:
    - name: make sure that we can connect to the machine
      ping:

    - name: ensure dev utils is installed
      package:
        name:
          - git
          - curl
          - mc
          - zsh
        state: present

