---
- hosts: all
  become: yes
  roles:
    - geerlingguy.git
    - { role: viasite-ansible.zsh, zsh_user: demas }

  tasks:
    - name: make sure that we can connect to the machine
      ping:

    - name: ensure dev utils is installed
      package:
        name:
          - curl
          - mc
        state: present

    - name: download micro
      get_url: 
        url: https://github.com/zyedidia/micro/releases/download/v1.4.1/micro-1.4.1-linux64.tar.gz
        dest: /tmp/micro.tar.gz

    - name: extract micro
      unarchive: src=/tmp/micro.tar.gz dest=/tmp copy=no

    - name: copy micro to /usr/bin directory
      command: cp /tmp/micro-1.4.1/micro /usr/bin/micro
